using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PointerImage : MonoBehaviour {
    [SerializeField]
    private Image pointerImage; // UI ภฬนฬม๖ธฆ วุด็ บฏผ๖ฟก ฟฌฐแ

    private void Update() {
        // ธถฟ์ฝบ ภงฤกธฆ ฑโมุภธทฮ UI ภฬนฬม๖ภว ภงฤกธฆ พ๗ตฅภฬฦฎ
        UpdatePointerPosition();
    }

    private void UpdatePointerPosition() {
        if (pointerImage != null) {
            // ธถฟ์ฝบภว ฝบลฉธฐ มยวฅธฆ ฐกมฎฟศ
            Vector3 mousePosition = Input.mousePosition;

            // UI มยวฅทฮ บฏศฏ
            RectTransform canvasRect = pointerImage.canvas.GetComponent<RectTransform>();
            Vector2 canvasSize = canvasRect.sizeDelta;
            Vector2 normalizedMousePosition = new Vector2(mousePosition.x / Screen.width, mousePosition.y / Screen.height);
            Vector2 uiPosition = new Vector2(normalizedMousePosition.x * canvasSize.x, normalizedMousePosition.y * canvasSize.y);

            // UI ภฬนฬม๖ภว ภงฤกธฆ พ๗ตฅภฬฦฎ
            pointerImage.rectTransform.anchoredPosition = uiPosition;
        }
    }
}
